apiVersion: v1
kind: Namespace
metadata:
  name: monitor
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-exporter
  namespace: bloginfer
  labels:
    app: mysql-exporter
spec:
  ports:
    - name: metrics
      port: 9104
      targetPort: 9104
  selector:
    app: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  namespace: bloginfer
  labels:
    app: nginx-exporter
spec:
  ports:
    - name: metrics
      port: 9113
      targetPort: 9113
  selector:
    app: nginx
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-sm
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: mysql-exporter
  namespaceSelector:
    matchNames: ["bloginfer"]
  endpoints:
    - port: metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-sm
  namespace: monitor
spec:
  selector:
    matchLabels:
      app: nginx-exporter
  namespaceSelector:
    matchNames: ["bloginfer"]
  endpoints:
    - port: metrics
      interval: 15s
---

