apiVersion: apps/v1
kind: Deployment
metadata:
  name: train
  namespace: bloginfer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: train
  template:
    metadata:
      labels:
        app: train
    spec:
      containers:
        - name: train
          image: pytorch/pytorch:2.9.0-cuda13.0-cudnn9-runtime
          command: ["bash", "-c"]
          args:
            - |
              cd /blog \
              && pip install -r train/requirements.txt \
              && python -u train/train.py \
              && sleep infinity
          volumeMounts:
            - name: blog-storage
              mountPath: /blog
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
      volumes:
        - name: blog-storage
          persistentVolumeClaim:
            claimName: blog-pvc
